# Create a program that will play the “cows and bulls” game with the user. The game works like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed
# correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is
# a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses
# the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell
# the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...
#
# Until the user guesses the number.
import random


def calcula_score(adivinhado, gerado):
    cow = 0
    bull = 0
    for digito in range(len(adivinhado)):
        if adivinhado[digito] == gerado[digito]:
            cow += 1
        else:
            bull += 1
    print(cow, "vaca" if cow == 1 else "vacas", bull, "touro" if bull == 1 else "touros")


def input_adivinhado():
    numero_adivinhado = ''
    try:
        while numero_adivinhado not in range(1000, 9999):
            numero_adivinhado = int(input("Digite um número entre 1000 e 9999: "))
    except ValueError:
        print("Digite um **NÚMERO** entre 1000 e 9999.")
    numero_adivinhado = str(numero_adivinhado)
    return numero_adivinhado


def cows_and_bulls():
    numero_gerado = str(random.randrange(1000, 9999))
    print(numero_gerado)
    numero_adivinhado = ''
    while numero_gerado != numero_adivinhado:
        numero_adivinhado = input_adivinhado()
        calcula_score(numero_adivinhado, numero_gerado)


cows_and_bulls()
